spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/cao_xiao_yu/tensquare_config.git
  rabbitmq:
    host: 192.168.154.29
server:
  port: 12000
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh