server:
  port: 9006
spring:
  application:
    name: tensquare_spit
  data:
    mongodb:
      host: 192.168.154.29
      database: test
  redis:
    host: 192.168.154.29
eureka:
  client:
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
          defaultZone: http://192.168.154.29:6868/eureka/
  instance:
    prefer-ip-address: true #在服务上跨域访问，本地要不要无所谓