server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.154.29:3306/tensquare_recruit?useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
eureka:
  client:
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
          defaultZone: http://192.168.154.29:6868/eureka/
  instance:
    prefer-ip-address: true #在服务上跨域访问，本地要不要无所谓