server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.154.29:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 192.168.154.29
  redis:
    host: 192.168.154.29
jwt:
  config:
    key: "itcast"
    ttl: 360000   #token时效一个小时
eureka:
  client:
    service-url: #Eureka客户端与Eureka服务端进行交互的地址
          defaultZone: http://192.168.154.29:6868/eureka/
  instance:
    prefer-ip-address: true #在服务上跨域访问，本地要不要无所谓